shelters_data = [
    {
        "shelter_number": 1,
        "address": "Hatikva Neighborhood Shelter, Tel Aviv",
        "capacity": 150,
        "longitude": 34.7736,
        "latitude": 32.0505,
        "utilities": {
            "Canned beans": 150,
            "Canned vegetables": 150,
            "Rice": 75,
            "Pasta": 75,
            "Canned fruit": 150,
            "soap": 150,
            "Instant oatmeal": 15,
            "tooth paste": 150,
            "toilet paper": 15,
            "Shelf-stable milk": 75,
        },
    },
    {
        "shelter_number": 2,
        "address": "Shelter 4, Tel Aviv",
        "capacity": 200,
        "longitude": 34.7760,
        "latitude": 32.0590,
        "utilities": {
            "Canned beans": 200,
            "Canned vegetables": 200,
            "Rice": 100,
            "Pasta": 100,
            "Canned fruit": 200,
            "soap": 200,
            "Instant oatmeal": 20,
            "tooth paste": 200,
            "toilet paper": 20,
            "Shelf-stable milk": 100,
        },
    },
    {
        "shelter_number": 3,
        "address": "Shelter 3, Tel Aviv",
        "capacity": 120,
        "longitude": 34.7701,
        "latitude": 32.0726,
        "utilities": {
            "Canned beans": 120,
            "Canned vegetables": 120,
            "Rice": 60,
            "Pasta": 60,
            "Canned fruit": 120,
            "soap": 120,
            "Instant oatmeal": 12,
            "tooth paste": 120,
            "toilet paper": 12,
            "Shelf-stable milk": 60,
        },
    },
    {
        "shelter_number": 4,
        "address": "Neve Sha'anan Shelter, Tel Aviv",
        "capacity": 180,
        "longitude": 34.7721,
        "latitude": 32.0416,
        "utilities": {
            "Canned beans": 180,
            "Canned vegetables": 180,
            "Rice": 90,
            "Pasta": 90,
            "Canned fruit": 180,
            "soap": 180,
            "Instant oatmeal": 18,
            "tooth paste": 180,
            "toilet paper": 18,
            "Shelf-stable milk": 90,
        },
    },
    {
        "shelter_number": 5,
        "address": "Shelter 5, Tel Aviv",
        "capacity": 100,
        "longitude": 34.7620,
        "latitude": 32.0548,
        "utilities": {
            "Canned beans": 100,
            "Canned vegetables": 100,
            "Rice": 50,
            "Pasta": 50,
            "Canned fruit": 100,
            "soap": 100,
            "Instant oatmeal": 10,
            "tooth paste": 100,
            "toilet paper": 10,
            "Shelf-stable milk": 50,
        },
    },
]
